### ISSUE TITLE
Bug fix i Product Details

### ISSUE THREAD

**Issue by KimmoKAhola** [KYH-Net23/Rika#234]
![{C815BB0F-7627-4528-95B6-347A602C5ED3}](https://github.com/user-attachments/assets/68011c31-d455-4d6e-bfec-a100957b255c)

fetchProductDetails() hämtas för många gånger och gör sidan seg. Tänk på att UseEffect körs varje gång en sida öppnas så använd den bara när den behövs.

- [x] Size måste ändras till ett objekt och varje produkt ska ha en lista av storlekar (S till XXL)
- [ ] Seedade värdena i databasen måste uppdateras så att de innehåller rätt storlekar.
- [x] Ta bort useEffect från Både ImageSection och DetailsSection. Båda filerna har sina egna anrop till fetchProducts i onödan. Skicka in en lista av produkter till dem istället.
- [x] Ändra price till number istället för string!
- [x] Lägg till size som information ni hämtar från backend.

**Comment by MosesDaCode** [comment]
Needs a new user story for defferent types of sizes for different types of products ex. clothing, shoes and electronics
